NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

In [3]:
import numpy as np 

Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Creating NumPy Arrays

In [13]:
#We can create an array by directly converting a list or list of lists:

my_list = [[1,2,3]]
my_list


[[1, 2, 3]]

In [14]:
np.array(my_list)


array([[1, 2, 3]])

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Built-in Methods

There are lots of built-in ways to generate Arrays

In [9]:

#arange
#Return evenly spaced values within a given interval.


np.arange(5,10)

array([5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

zeros and ones

In [5]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [6]:
a.shape

(3,)

In [26]:
a

array([0., 0., 0.])

In [7]:
b = np.zeros((5,4)) 
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
b.shape  

(5, 4)

In [18]:
a.shape

(3,)

In [8]:
x = a.reshape(1,3)
x.shape


(1, 3)

In [9]:
x

array([[0., 0., 0.]])

In [27]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

linspace

Return evenly spaced numbers over a specified interval.

In [12]:

np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

eye

Creates an identity matrix

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random

Numpy also has lots of ways to create random number arrays:

rand

Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [33]:
np.random.rand(2)

array([0.76700312, 0.20892631])

In [34]:
np.random.rand(5,5)

array([[0.58139074, 0.9889914 , 0.27135303, 0.37335848, 0.07317809],
       [0.54469156, 0.5978762 , 0.05194064, 0.03354184, 0.5686522 ],
       [0.80967632, 0.39046913, 0.97009931, 0.68414786, 0.72508279],
       [0.32448331, 0.02398273, 0.73622221, 0.83528506, 0.46819995],
       [0.08366403, 0.71097369, 0.01019857, 0.56234918, 0.46813346]])

randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [21]:
np.random.randn(2)

array([ 0.15754276, -0.25366942])

In [35]:

np.random.randn(5,5)

array([[ 1.45375265e-01, -5.09783706e-01, -3.21680565e-01,
        -8.86308175e-01, -3.92056643e-01],
       [ 1.30064139e+00,  3.16968565e-01, -5.75524881e-01,
         7.44442907e-01,  5.75830717e-01],
       [-1.54593026e-01, -1.67037814e+00,  4.76642197e-01,
         5.78835807e-01, -6.32253537e-01],
       [ 7.79538419e-04, -1.22190738e+00, -6.43902716e-01,
         5.67793775e-01, -6.60248079e-01],
       [ 1.07510676e+00, -5.04027471e-01,  9.39010624e-01,
         2.03414504e+00,  8.12691768e-01]])

randint

Return random integers from low (inclusive) to high (exclusive).

In [36]:

np.random.randint(1,100)

68

In [37]:

np.random.randint(1,100,10)

array([55, 36, 95, 38, 53, 17, 88, 58, 81, 43])

In [16]:
# Array Attributes and Methods
# Let's discuss some useful attributes and methods or an array:

import numpy as np
arr = np.arange(25)
print(arr)
ranarr = np.random.randint(0,50,10)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[28 25 37 25 49 13 26 21 40 26]


Reshape

Returns an array containing the same data with a new shape.

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.shape

(25,)

In [19]:
b = arr.reshape(5,5)

In [20]:
b.shape

(5, 5)

In [33]:
c = b.reshape(25,1)
c

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [31]:
d = c.shape
d

(25, 1)

max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [53]:
ranarr


array([48,  9, 16, 46, 26, 31, 15,  0,  8, 12])

In [28]:

ranarr.max()

48

In [55]:
ranarr.argmax()  # return position

0

In [56]:
ranarr.min()

0

In [57]:

ranarr.argmin()

7

Shape

Shape is an attribute that arrays have (not a method):

In [11]:
# Vector
arr.shape 

(25,)

In [33]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
arr.reshape(1,25).shape

(1, 25)

In [35]:

arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [36]:
arr.reshape(25,1).shape

(25, 1)

dtype

You can also grab the data type of the object in the array:

In [58]:
type(arr)

numpy.ndarray

In [59]:
arr.dtype

dtype('int32')

In [60]:
type(arr[0])

numpy.int32

NumPy Indexing and Selection

In [62]:
#Creating sample array
arr = np.arange(0,11)

#Show
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Bracket Indexing and Selection

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [63]:
#Get a value at an index
arr[8]

8

In [64]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [65]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [69]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [45]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [46]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [47]:
#Data is not copied, it's a view of the original array! This avoids memory problems!

#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing a 2D array (matrices)

The general format is arr_2d[row][col] or arr_2d[row,col]. I recommend usually using the comma notation for clarity.

In [70]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [73]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [74]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [75]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [76]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [77]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [78]:
#Set up matrix
arr2d = np.zeros((10,10))

#Length of array
arr_length = arr2d.shape[1]

In [81]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [82]:
#Fancy indexing allows the following


arr2d[[2,4,6,8]]   

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [83]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

Selection

In [10]:
arr = np.arange(1,11)
arr  

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [86]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [61]:

bool_arr = arr>4

In [62]:

bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [63]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [64]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

NumPy Operations

In [66]:

import numpy as np
arr = np.arange(0,10)

In [67]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [68]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [69]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [70]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

<ipython-input-70-2f119c028196>:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
# Also warning, but not an error instead infinity
1/arr

<ipython-input-71-c81c9b6169c9>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [72]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

Universal Array Functions

Numpy comes with many universal array functions, which are essentially just mathematical operations you can use to perform the operation across the array. 

In [73]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [74]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [75]:
np.max(arr) #same as arr.max()

9

In [76]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [77]:
np.log(arr)

<ipython-input-77-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np_list_one = np.array([1,2,3])
np_list_two = np.array([4,5,6])

In [ ]:
np_list_one.append(np_list_two)