In [1]:
# pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries.

- Most powerful numerical processing library in python. 
- Array Oriented computing.
- Provides extension package to python for multi dimensional array.
- Very efficient.
- Scientific computation.

In [4]:
# Install a pip package in the current Jupyter kernel
# ! pip install numpy


"""
"Pip" is the package installer for Python. It's a command-line tool that allows you to install, manage, and uninstall Python packages 
from the Python Package Index (PyPI) or other package indexes. 
PyPI is a repository of software packages developed and contributed by Python community members.
"""

But WHY numpy, when we already have lists?

In [1]:
%%time

lst = list(range(1000000));

for i in range(1000000):
    lst[i] *= lst[i]

CPU times: total: 141 ms
Wall time: 146 ms


In [5]:
%%time

arr = np.arange(1000000)

arr = arr * arr

CPU times: total: 15.6 ms
Wall time: 3.03 ms


Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Creating NumPy Arrays

In [12]:
#We can create an array by directly converting a list or list of lists:

lst = [1, 2, 3, 4, 5, 6, 7]

print(type(lst))

print("List: ", lst)

my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

print(type(my_matrix))

print("List: ", my_matrix)

<class 'list'>
List:  [1, 2, 3, 4, 5, 6, 7]
<class 'list'>
List:  [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [13]:
import numpy as np

arr = np.array(lst)

print(type(arr))

print("Numpy Array: ", arr)

my_np_matrix = np.array(my_matrix)
 
print(type(my_np_matrix))

print("List: ", my_np_matrix)

<class 'numpy.ndarray'>
Numpy Array:  [1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
List:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# Creating a simple array in numpy using np.arange

#arange
#Return evenly spaced values within a given interval.
arr = np.arange(10)

print(type(arr))

print("Numpy Array: ", arr)

#np.arange(0,11,2)
#np.arange(0,11,2)

<class 'numpy.ndarray'>
Numpy Array:  [0 1 2 3 4 5 6 7 8 9]


Numpy Array and It's Attributes/Properties

In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [1 2 3 4]
Shape:  (4,)
Data Type:  int32
Item Size:  4
Dimensionality:  1


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Data Type:  int32
Item Size:  4
Dimensionality:  2


Built-in Methods

There are lots of built-in ways to generate Arrays

zeros and ones

In [17]:
arr = np.zeros((3, 3))

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [18]:
arr = np.ones((3, 3))

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [19]:
arr = np.eye(3)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape:  (3, 3)
Data Type:  float64
Item Size:  8
Dimensionality:  2


In [20]:
arr = np.eye(3, 2)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [[1. 0.]
 [0. 1.]
 [0. 0.]]
Shape:  (3, 2)
Data Type:  float64
Item Size:  8
Dimensionality:  2


linspace

Return evenly spaced numbers over a specified interval.

In [21]:

arr = np.linspace(0,10,3)

print("Array: \n", arr)

# Print shape
print("Shape: ", arr.shape)

# Print datatype
print("Data Type: ", arr.dtype)

# Print item size in byte of each element
print("Item Size: ", arr.itemsize)

# Print the dimensionality of the numpy array
print("Dimensionality: ", arr.ndim)

Array: 
 [ 0.  5. 10.]
Shape:  (3,)
Data Type:  float64
Item Size:  8
Dimensionality:  1


## Datatypes in Numpy

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- str - string
- f - float
- m - timedelta
- M - datetime
- O - object
- u - unsigned integer
- c - complex float
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [22]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='f')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2. 1. 4. 5.]
Data Type:  float32


In [23]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='O')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 [2 1 4 5]
Data Type:  object


In [24]:
import numpy as np

arr = np.array([2, 1, 4, 5], dtype='str')

print("Array: \n", arr)

# Print datatype
print("Data Type: ", arr.dtype)

Array: 
 ['2' '1' '4' '5']
Data Type:  <U1


## Numpy Random Numbers

1. **np.random.rand** - generates an array with random numbers that are uniformly distribute between 0 and 1.
2. **np.random.randn** - generates an array with random numbers that are normally distributed, mean = 0 and stdev = 1.
3. **np.random.randint** - generates an array with random numbers (integers) that are uniformly distribute between 0 and given number.
4. **np.random.uniform** - generates an array with random numbers (float) between given numbers.

In [26]:
# Randomly generate an array from uniform distribution
import numpy as np

arr = np.random.rand(5) # np.random.rand(10, 2)

print("Numpy Array: \n", arr)

# Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

Numpy Array: 
 [0.85453162 0.55399779 0.21306772 0.96142873 0.69805756]


In [27]:
# Randomly generate an array from normal distribution
import numpy as np

arr = np.random.randn(5) # np.random.randn(5, 4)

print("Numpy Array: \n", arr)

# Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

Numpy Array: 
 [ 0.58861918 -2.79049659 -0.08597498 -1.07591865  1.15272067]


In [31]:
# Generate one random integer between 0 to 9

value = np.random.randint(10)

print(value)

# Return random integers from low (inclusive) to high (exclusive).

print(np.random.randint(1,100,10))

# Randomly generate a 5*4 array containing values in the range of 0 to 9
arr = np.random.randint(10, size = (5, 4))
print("Numpy Array: \n", arr)

# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))
print("Numpy Array: \n", arr)

3
[47 22 76 23 53  2 69 30 67 43]
Numpy Array: 
 [[4 5 7 2]
 [0 6 3 6]
 [6 2 4 3]
 [5 8 1 4]
 [1 9 6 3]]
Numpy Array: 
 [[12 36 38 23 30 16 37 31 32 19]
 [25 17 30 35 12 37 37 29 18 18]
 [25 16 33 35 16 35 37 32 23 15]
 [38 18 31 21 21 11 39 18 30 37]
 [12 29 33 25 12 26 28 31 24 30]]


In [33]:
# Generate one random decimal value between 0 to 10
value = np.random.uniform(10)
print(value)

# Randomly generate a 5*4 array containing values in the range of 0 to 10
arr = np.random.uniform(10, size = (5, 4))
print("Numpy Array: \n", arr)


# Randomly generate a 5*3 array containing values in the range of 10 to 40
arr = np.random.uniform(10, 40, size = (5, 3))
print("Numpy Array: \n", arr)

2.5549495363926953
Numpy Array: 
 [[1.48045003 3.5094456  4.6879908  4.02912981]
 [4.87928387 3.01079399 6.24219088 6.41454789]
 [6.38143769 9.24110639 3.3322911  6.62797793]
 [1.42401305 6.66956556 1.33481784 8.39598939]
 [6.28949485 9.13631381 2.52473138 9.13908103]]
Numpy Array: 
 [[34.08706427 33.34768084 25.24602199]
 [36.42759346 18.49469898 11.66951271]
 [26.03460679 34.16334716 14.56825923]
 [26.28150973 13.64781669 25.23061204]
 [28.70414975 14.17097805 23.82689817]]


Data Accessing using `Indexing` in Numpy Array

In [35]:
# Randomly generating 1 dimensional array
arr = np.random.randint(100, size = (5, ))
print("Numpy Array: \n", arr)
# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

Numpy Array: 
 [18  8  8 35 27]
Value at 2nd index:  8


In [36]:
# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))
print("Numpy Array: \n", arr)


# Accessing 2nd index
print("Value at 2nd index: ", arr[2])

# Accessing value at 2, 1 index
print("Accessing Value using Way-1: ", arr[2][1])

print("Accessing Value using Way-2: ", arr[2, 1]) 
# Way-2 syntax can be helpful to access multiple values

Numpy Array: 
 [[17 95  0 95]
 [77 16 94 13]
 [47  1  6 66]
 [89  6 82 85]
 [34 37 92 79]]
Value at 2nd index:  [47  1  6 66]
Accessing Value using Way-1:  1
Accessing Value using Way-2:  1


In [42]:
# Accesssing multiple values
 # Create a 2D NumPy array
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Perform advanced indexing
result = arr[[2, 1], [1, 1]]

# The first index array [2, 1] refers to the indices along the first axis (typically rows).
# The second index array [1, 1] refers to the indices along the second axis (typically columns).


# Print the result
print(result)

[7 4]


In [43]:
print(arr[1:4])

[[3 4 5]
 [6 7 8]]


In [44]:
# # Remember Way-2 for accessing the data in Numpy array
print(arr[:2, 1:3])
# print(arr[1:2, :])

[[1 2]
 [4 5]]


Indexing with Boolean Arrays

In [45]:
# Randomly generating 1 dimensional array
import numpy as np

arr = np.random.randint(100, size = (10, ))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

idx = [True, False, False, False, False, True, False, False, True, True]

print(arr[idx])

Numpy Array: 
 [59 17 66  4  0 60 38 22  7 53]
Shape:  (10,)
[59 60  7 53]


In [46]:
# Updating value in the array

# Randomly generating 2 dimensional array
arr = np.random.randint(100, size = (5, 4))

print("Original Array: \n", arr)

arr[1, 1] = 99

print("Updated Array: \n", arr)

Original Array: 
 [[95 41  4 51]
 [35 39 16 82]
 [75 20 79 38]
 [92 74 73 53]
 [42  4 94 30]]
Updated Array: 
 [[95 41  4 51]
 [35 99 16 82]
 [75 20 79 38]
 [92 74 73 53]
 [42  4 94 30]]


Numpy Flatten and Ravel

In [47]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[23 11 10 38 17 13 38 13 37 38]
 [18 18 11 29 11 10 38 11 10 22]
 [12 35 35 37 22 10 27 14 29 11]
 [27 19 30 29 23 24 30 15 28 17]
 [18 36 11 37 29 21 29 31 30 31]]
Shape:  (5, 10)


In [48]:
flatten_arr = arr.flatten()

print("Flatten Array: \n", flatten_arr)
print("Shape: ", flatten_arr.shape)

Flatten Array: 
 [23 11 10 38 17 13 38 13 37 38 18 18 11 29 11 10 38 11 10 22 12 35 35 37
 22 10 27 14 29 11 27 19 30 29 23 24 30 15 28 17 18 36 11 37 29 21 29 31
 30 31]
Shape:  (50,)


In [49]:
ravel_arr = arr.ravel()

print("Ravel Array: \n", ravel_arr)
print("Shape: ", ravel_arr.shape)

Ravel Array: 
 [23 11 10 38 17 13 38 13 37 38 18 18 11 29 11 10 38 11 10 22 12 35 35 37
 22 10 27 14 29 11 27 19 30 29 23 24 30 15 28 17 18 36 11 37 29 21 29 31
 30 31]
Shape:  (50,)


Ravel is faster than flatten() as it does not occupy any memory. Ravel returns a view of the original array.

Numpy Reshape

Returns an array containing the same data with a new shape.

In [50]:
# Randomly generate a 5*10 array containing values in the range of 10 to 39
arr = np.random.randint(10, 40, size = (5, 10))

print("Numpy Array: \n", arr)

print("Shape: ", arr.shape)

Numpy Array: 
 [[27 31 11 11 38 25 18 17 26 35]
 [28 28 21 12 22 17 27 22 31 36]
 [15 33 33 29 24 37 11 27 38 18]
 [20 15 16 32 17 10 32 22 35 26]
 [31 36 33 32 26 30 32 22 19 22]]
Shape:  (5, 10)


In [51]:
arr_reshaped = arr.reshape(10, 5)

print(arr_reshaped)

[[27 31 11 11 38]
 [25 18 17 26 35]
 [28 28 21 12 22]
 [17 27 22 31 36]
 [15 33 33 29 24]
 [37 11 27 38 18]
 [20 15 16 32 17]
 [10 32 22 35 26]
 [31 36 33 32 26]
 [30 32 22 19 22]]


In [52]:
arr_reshaped = arr.reshape(25, 2)

print(arr_reshaped)

[[27 31]
 [11 11]
 [38 25]
 [18 17]
 [26 35]
 [28 28]
 [21 12]
 [22 17]
 [27 22]
 [31 36]
 [15 33]
 [33 29]
 [24 37]
 [11 27]
 [38 18]
 [20 15]
 [16 32]
 [17 10]
 [32 22]
 [35 26]
 [31 36]
 [33 32]
 [26 30]
 [32 22]
 [19 22]]


In [53]:
arr_reshaped = arr.reshape(3, 3)

print(arr_reshaped)

ValueError: cannot reshape array of size 50 into shape (3,3)

Python Operators on Numpy Array

In [54]:
# We can apply any python operator on Numpy Array.
# It will perform the operation on each element of a numpy array.

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

Original Array: 
 [[1 2 3]
 [4 5 6]]


In [55]:
print(x + 5)

[[ 6  7  8]
 [ 9 10 11]]


In [56]:
print(x % 2)

[[1 0 1]
 [0 1 0]]


In [57]:
print(x >= 3)

[[False False  True]
 [ True  True  True]]


In [58]:
print(x % 2 == 0)

[[False  True False]
 [ True False  True]]


Numpy Maths

Reference: https://numpy.org/doc/stable/reference/routines.math.html

In [59]:
print("Square Root: ", np.sqrt(4))

print("Exponent: ", np.exp(1))

print("Trigonometric Sin: ", np.sin(0))

print("Trigonometric Cos: ", np.cos(0))

print("... and many more")

Square Root:  2.0
Exponent:  2.718281828459045
Trigonometric Sin:  0.0
Trigonometric Cos:  1.0
... and many more


In [60]:
arr = np.array([1, 2, 3, 4])

print("Square Root: ", np.sqrt(arr))

print("Exponent: ", np.exp(arr))

print("Trigonometric Sin: ", np.sin(arr))

print("Trigonometric Cos: ", np.cos(arr))

Square Root:  [1.         1.41421356 1.73205081 2.        ]
Exponent:  [ 2.71828183  7.3890561  20.08553692 54.59815003]
Trigonometric Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Trigonometric Cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [61]:
# ELEMENT WISE OPERATIONS

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Elementwise Addition: \n", np.add(x, y))

print("Elementwise Subtraction: \n", np.subtract(x, y))

print("Elementwise Multiplication: \n", np.multiply(x, y))

print("Elementwise Division: \n", np.divide(x, y))

Elementwise Addition: 
 [[ 6  8]
 [10 12]]
Elementwise Subtraction: 
 [[-4 -4]
 [-4 -4]]
Elementwise Multiplication: 
 [[ 5 12]
 [21 32]]
Elementwise Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [62]:
# Matrix Multiplication
import numpy as np

x = np.array([[1,2], [3,4]])

y = np.array([[5,6], [7,8]])

print("Matrix Multiplication (Way-1): \n", np.matmul(x, y))

print("Matrix Multiplication (Way-2): \n", np.dot(x, y))

print("Matrix Multiplication (Way-3): \n", x @ y)

Matrix Multiplication (Way-1): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-2): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-3): 
 [[19 22]
 [43 50]]


In [63]:
# Diagonal elements

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print("Diagonal: ", np.diag(x))

Original Array: 
 [[1 2 3]
 [4 5 6]]
Diagonal:  [1 5]


In [64]:
# Transpose of an array

x = np.array([[1, 2, 3], [4, 5, 6]])

print("Original Array: \n", x)

print()

print("Transpose: \n", x.T)

Original Array: 
 [[1 2 3]
 [4 5 6]]

Transpose: 
 [[1 4]
 [2 5]
 [3 6]]


Numpy Statistics

In [65]:
x = np.array([[1,2], [3,4]])

print("Array: \n", arr)

print("Sum: ", np.sum(x))

print("Columnwise Sum: ", np.sum(x, axis=0)) # Column Wise

print("Rowwise Sum: ", np.sum(x, axis=1)) # Row wise

Array: 
 [1 2 3 4]
Sum:  10
Columnwise Sum:  [4 6]
Rowwise Sum:  [3 7]


In [66]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Columnwise Minimum: ", np.min(x, axis=0)) # Column Wise

print("Rowwise Minimum: ", np.min(x, axis=1)) # Row wise

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Columnwise Minimum:  [1 2 3]
Rowwise Minimum:  [1 4]


In [67]:
x = np.array([160, 180, 146, 162, 184, 180])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [160 180 146 162 184 180]
Minimum:  146
Maximum:  184
Mean:  168.66666666666666
Median:  171.0
Variance:  187.55555555555557
Std Dev:  13.695092389449425


In [68]:
x = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", x)

print("Minimum: ", np.min(x))

print("Maximum: ", np.max(x))

print("Mean: ", np.mean(x))

print("Median: ", np.median(x))

print("Variance: ", np.var(x))

print("Std Dev: ", np.std(x))

Array: 
 [[1 2 3]
 [4 5 6]]
Minimum:  1
Maximum:  6
Mean:  3.5
Median:  3.5
Variance:  2.9166666666666665
Std Dev:  1.707825127659933


In [69]:
heights = np.array([160, 180, 146, 162, 184, 180])

weights = np.array([50, 78, 45, 51, 80, 60])

np.corrcoef(heights, weights)

array([[1.        , 0.88546942],
       [0.88546942, 1.        ]])

 Sorting

In [70]:
import numpy as np

arr = np.random.randint(50, 100, size = (5, 10))

print(arr)

[[52 62 99 83 77 64 54 91 66 62]
 [83 91 96 73 88 62 90 59 76 65]
 [98 59 84 69 57 94 88 99 99 69]
 [56 54 50 72 69 59 84 83 83 68]
 [64 63 57 73 90 70 50 54 90 69]]


In [71]:
np.sort(arr)

array([[52, 54, 62, 62, 64, 66, 77, 83, 91, 99],
       [59, 62, 65, 73, 76, 83, 88, 90, 91, 96],
       [57, 59, 69, 69, 84, 88, 94, 98, 99, 99],
       [50, 54, 56, 59, 68, 69, 72, 83, 83, 84],
       [50, 54, 57, 63, 64, 69, 70, 73, 90, 90]])

In [72]:
# Column Wise Sorting

np.sort(arr, axis = 0)

array([[52, 54, 50, 69, 57, 59, 50, 54, 66, 62],
       [56, 59, 57, 72, 69, 62, 54, 59, 76, 65],
       [64, 62, 84, 73, 77, 64, 84, 83, 83, 68],
       [83, 63, 96, 73, 88, 70, 88, 91, 90, 69],
       [98, 91, 99, 83, 90, 94, 90, 99, 99, 69]])

In [73]:
# Row Wise Sorting

np.sort(arr, axis = 1)

array([[52, 54, 62, 62, 64, 66, 77, 83, 91, 99],
       [59, 62, 65, 73, 76, 83, 88, 90, 91, 96],
       [57, 59, 69, 69, 84, 88, 94, 98, 99, 99],
       [50, 54, 56, 59, 68, 69, 72, 83, 83, 84],
       [50, 54, 57, 63, 64, 69, 70, 73, 90, 90]])

Stacking

"stacking" typically refers to combining arrays along a new axis.

In [74]:
arr_1 = np.arange(5,15).reshape(2,5)

print(arr_1)

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [75]:
arr_2 = np.arange(25,35).reshape(2,5)
print(arr_2)

[[25 26 27 28 29]
 [30 31 32 33 34]]


In [76]:
np.vstack([arr_1, arr_2])

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [77]:
np.hstack([arr_1, arr_2])

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

Concatenate

In [78]:
np.concatenate([arr_1, arr_2], axis = 0) # concatinating - vertical stacking

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [79]:
np.concatenate([arr_1, arr_2], axis = 1) # concatinating - horizontal stacking

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

Append

In [80]:
np.append(arr_1, arr_2, axis = 0) # Appending - vertical stacking

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [81]:
np.append(arr_1, arr_2, axis = 1) # Appending - horizontal stacking

array([[ 5,  6,  7,  8,  9, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 30, 31, 32, 33, 34]])

Where - Process Array Elements Conditionally

Understanding np.where() Syntax 
```python
numpy.where(  
  condition,   # Where True, yield x, otherwise y  
  [x, y, ]     # Values to choose from  
)  
```

In [82]:
arr = np.arange(50, 100).reshape(5, 10)

print(arr)

[[50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [84]:
np.where(arr > 64, 0, 1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [85]:
np.where(arr > 64, arr/10, arr)

array([[50. , 51. , 52. , 53. , 54. , 55. , 56. , 57. , 58. , 59. ],
       [60. , 61. , 62. , 63. , 64. ,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])